//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscapeRankUI.Recursos {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EscapeRankUI.Recursos.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string inicio {
            get {
                return ResourceManager.GetString("inicio", resourceCulture);
            }
        }
        
        internal static string partida {
            get {
                return ResourceManager.GetString("partida", resourceCulture);
            }
        }
        
        internal static string popular_ahora {
            get {
                return ResourceManager.GetString("popular_ahora", resourceCulture);
            }
        }
        
        internal static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        internal static string ver_todo {
            get {
                return ResourceManager.GetString("ver_todo", resourceCulture);
            }
        }
        
        internal static string publico {
            get {
                return ResourceManager.GetString("publico", resourceCulture);
            }
        }
        
        internal static string explorar {
            get {
                return ResourceManager.GetString("explorar", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        internal static string dificultad {
            get {
                return ResourceManager.GetString("dificultad", resourceCulture);
            }
        }
        
        internal static string salas {
            get {
                return ResourceManager.GetString("salas", resourceCulture);
            }
        }
        
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        internal static string datos {
            get {
                return ResourceManager.GetString("datos", resourceCulture);
            }
        }
        
        internal static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        internal static string historial {
            get {
                return ResourceManager.GetString("historial", resourceCulture);
            }
        }
        
        internal static string ganada_en {
            get {
                return ResourceManager.GetString("ganada_en", resourceCulture);
            }
        }
        
        internal static string realizado_en {
            get {
                return ResourceManager.GetString("realizado_en", resourceCulture);
            }
        }
        
        internal static string tiempo_sala {
            get {
                return ResourceManager.GetString("tiempo_sala", resourceCulture);
            }
        }
        
        internal static string equipo {
            get {
                return ResourceManager.GetString("equipo", resourceCulture);
            }
        }
        
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        internal static string amigos {
            get {
                return ResourceManager.GetString("amigos", resourceCulture);
            }
        }
        
        internal static string equipos {
            get {
                return ResourceManager.GetString("equipos", resourceCulture);
            }
        }
        
        internal static string hora {
            get {
                return ResourceManager.GetString("hora", resourceCulture);
            }
        }
        
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        internal static string fecha_nacimiento {
            get {
                return ResourceManager.GetString("fecha_nacimiento", resourceCulture);
            }
        }
        
        internal static string iniciar_sesion {
            get {
                return ResourceManager.GetString("iniciar_sesion", resourceCulture);
            }
        }
        
        internal static string duracion_sala {
            get {
                return ResourceManager.GetString("duracion_sala", resourceCulture);
            }
        }
        
        internal static string duracion_partida {
            get {
                return ResourceManager.GetString("duracion_partida", resourceCulture);
            }
        }
        
        internal static string validar_partida {
            get {
                return ResourceManager.GetString("validar_partida", resourceCulture);
            }
        }
        
        internal static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        internal static string registrarse {
            get {
                return ResourceManager.GetString("registrarse", resourceCulture);
            }
        }
        
        internal static string registrar {
            get {
                return ResourceManager.GetString("registrar", resourceCulture);
            }
        }
        
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        internal static string ingresar {
            get {
                return ResourceManager.GetString("ingresar", resourceCulture);
            }
        }
        
        internal static string edad {
            get {
                return ResourceManager.GetString("edad", resourceCulture);
            }
        }
        
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        internal static string partidas_ganadas {
            get {
                return ResourceManager.GetString("partidas_ganadas", resourceCulture);
            }
        }
        
        internal static string partidas_perdidas {
            get {
                return ResourceManager.GetString("partidas_perdidas", resourceCulture);
            }
        }
        
        internal static string total_partidas {
            get {
                return ResourceManager.GetString("total_partidas", resourceCulture);
            }
        }
        
        internal static string mejor_tiempo {
            get {
                return ResourceManager.GetString("mejor_tiempo", resourceCulture);
            }
        }
        
        internal static string entrar {
            get {
                return ResourceManager.GetString("entrar", resourceCulture);
            }
        }
        
        internal static string registrate {
            get {
                return ResourceManager.GetString("registrate", resourceCulture);
            }
        }
        
        internal static string eslogan {
            get {
                return ResourceManager.GetString("eslogan", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string contrasenya {
            get {
                return ResourceManager.GetString("contrasenya", resourceCulture);
            }
        }
        
        internal static string repetir_contrasenya {
            get {
                return ResourceManager.GetString("repetir_contrasenya", resourceCulture);
            }
        }
        
        internal static string selecciona_equipo {
            get {
                return ResourceManager.GetString("selecciona_equipo", resourceCulture);
            }
        }
        
        internal static string contrasenya_olvidada {
            get {
                return ResourceManager.GetString("contrasenya_olvidada", resourceCulture);
            }
        }
        
        internal static string pregunta_cuenta {
            get {
                return ResourceManager.GetString("pregunta_cuenta", resourceCulture);
            }
        }
        
        internal static string pregunta_crea_cuenta {
            get {
                return ResourceManager.GetString("pregunta_crea_cuenta", resourceCulture);
            }
        }
        
        internal static string entrar_con_facebook {
            get {
                return ResourceManager.GetString("entrar_con_facebook", resourceCulture);
            }
        }

        internal static string hacer_foto
        {
            get
            {
                return ResourceManager.GetString("hacer_foto", resourceCulture);
            }
        }

        internal static string cree_cuenta {
            get {
                return ResourceManager.GetString("cree_cuenta", resourceCulture);
            }
        }
        
        internal static string instrucciones_contrasenya {
            get {
                return ResourceManager.GetString("instrucciones_contrasenya", resourceCulture);
            }
        }

        internal static string provincia {
            get {
                return ResourceManager.GetString("provincia", resourceCulture);
            }
        }

        internal static string tematica
        {
            get
            {
                return ResourceManager.GetString("tematica", resourceCulture);
            }
        }

    }
}
